"""
Default Brand Mapping

Extracted directly from Sagar's ground truth reference file
(HC_KWP_Working_CompanyWise), covering every Brand_SKU_Item seen across
all formats (SHC, Creme, Henna, HBP, OBL, VAP, BP, KM) with its correct
Flag classification (Category / Brand / Sub-brand / Others).

This is used as the first-priority lookup when classifying rows from a
new raw file. Anything not found here falls back to the bracket-pattern
heuristic (see cleaner.classify_flag). Edit or replace this via the
dashboard's Brand Mapping section, changes there override this file
for that session and can be saved back out for next time.
"""

DEFAULT_BRAND_MAPPING = {
    '5 Star': 'Brand',
    '[COLOR] ANY COLORMATE CREME [ANY CR ME]': 'Brand',
    '[COLOR] ANY GARNIER OVERALL [ANY CR ME]': 'Brand',
    '[COLOR] ANY INDICA CREME [ANY CR ME]': 'Brand',
    '[COLOR] ANY OTHER BRANDED CREME [ANY CR ME]': 'Others',
    '[COLOR] ANY STREAX CREME [ANY CR ME]': 'Brand',
    '[HCEXL] 5 STAR': 'Brand',
    '[HCEXL] ABIHA POWDER [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] ADORE HENNA [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] AFRIN HENNA [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] AMINA HENNA [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] AMWAY': 'Brand',
    '[HCEXL] ANY BASIC POWDERS': 'Category',
    '[HCEXL] ANY CR ME': 'Category',
    '[HCEXL] ANY HAIR COL.SHAMPOO': 'Category',
    '[HCEXL] ANY HERBAL BASED PWD': 'Category',
    '[HCEXL] ANY OBL': 'Category',
    '[HCEXL] ANY POWDER KM NEW': 'Category',
    '[HCEXL] ANY VALUE ADDED PWDERS': 'Category',
    '[HCEXL] AYU  HENNA [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] BANJARA HENNA [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] BBLUNT': 'Brand',
    '[HCEXL] BIGEN B INSTANT COLOUR': 'Brand',
    '[HCEXL] BLACK DIAMOND DYE': 'Brand',
    '[HCEXL] BLACK DIAMOND HERBAL [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] BLACK DIAMOND KAL.MEHENDI': 'Brand',
    '[HCEXL] BLACK NITE KALI MEHANDI': 'Brand',
    '[HCEXL] BLACK ROSE HAIR COLOR': 'Brand',
    '[HCEXL] BLACK ROSE HENNA POWDER': 'Brand',
    '[HCEXL] BLACK ROSE KALI MEHANDI': 'Brand',
    '[HCEXL] BLACK ROSE POWDER DYE': 'Brand',
    '[HCEXL] BLACK ROSE SHAMPOO': 'Brand',
    '[HCEXL] BRITE HENNA [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] CHANDAN HERBAL POWDER [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] CHIK HAIR COLOUR SHAMPOO': 'Brand',
    '[HCEXL] CHIK KALI MEHANDI': 'Brand',
    '[HCEXL] CHIK QUICK CREME': 'Brand',
    '[HCEXL] CLEO': 'Brand',
    '[HCEXL] COLOR STAY HAIRCOLOR': 'Brand',
    '[HCEXL] COLORMATE [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] DIAMOND HENNA HAIR COLOR [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] EXCEL': 'Brand',
    '[HCEXL] FARISHTA': 'Brand',
    '[HCEXL] GARNIER BLACK NATURALS': 'Sub-brand',
    '[HCEXL] GARNIER COLOUR NATRALS': 'Sub-brand',
    '[HCEXL] GARNIER MEN SHAMPOO COLOUR SHAMPOO': 'Brand',
    '[HCEXL] GODREJ EXP EASY 5 MIN COLOR SHAMPOO': 'Brand',
    '[HCEXL] GODREJ EXPE RICH CR ME FASHION RANGE': 'Brand',
    '[HCEXL] GODREJ EXPERT ADVANCED PWD(PINK)': 'Brand',
    '[HCEXL] GODREJ EXPERT CARE PWD(GREEN) [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] GODREJ EXPERT NEW PWD(BLUEPACK)': 'Brand',
    '[HCEXL] GODREJ EXPERT ORIGINAL PWD(BLUE)': 'Brand',
    '[HCEXL] GODREJ EXPERT POWDER HAIR COLO': 'Brand',
    '[HCEXL] GODREJ EXPERT POWDER HAIR DYE': 'Brand',
    '[HCEXL] GODREJ EXPERT RICH CREME': 'Brand',
    '[HCEXL] GODREJ FASHION COLOUR': 'Brand',
    '[HCEXL] GODREJ KALI MAHENDEI': 'Brand',
    '[HCEXL] GODREJ KESH KALA HAIR OIL': 'Brand',
    '[HCEXL] GODREJ NUPUR CREME': 'Brand',
    '[HCEXL] GODREJ PERMENANT POW.HAIR DYE': 'Brand',
    '[HCEXL] GODREJ PROESSIONAL COLOURPLAY CREAM HAIR': 'Brand',
    '[HCEXL] GODREJ PROF.DIMENSION CREAM HAIR COLOR': 'Brand',
    '[HCEXL] GODREJ RENEW HAIR COLOUR CREAM': 'Brand',
    '[HCEXL] GODREJ RENEW POWDER HAIR COLOUR': 'Brand',
    '[HCEXL] GODREJ SELFIE HAIR COLOUR SHAMPOO': 'Brand',
    '[HCEXL] GRAM UDYOG POWDER [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] HAIR4REAL': 'Brand',
    '[HCEXL] HERBAL CHANDI DYE POWDER': 'Brand',
    '[HCEXL] INDICA': 'Brand',
    '[HCEXL] INDICA [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] JOVEES': 'Brand',
    '[HCEXL] KAISH KALA HERBAL OIL': 'Brand',
    '[HCEXL] KAJAL HAIR HENNA [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] KHADIGRAM POWDER [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] KORRA COLORING SHAMPOO': 'Brand',
    '[HCEXL] LIVON': 'Brand',
    '[HCEXL] LOREAL': 'Brand',
    '[HCEXL] MAHURI HENNA [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] MATRIX SOCOLOR PREBONDED CREAM HAIR COLO': 'Brand',
    '[HCEXL] MAYURI HENNA [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] MODICARE SALON PROFESSIONAL': 'Brand',
    '[HCEXL] MOON STAR [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] MSG [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] NEHA CREME': 'Brand',
    '[HCEXL] NEHA HENNA [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] NEHA KALI MEHANDI': 'Brand',
    '[HCEXL] NEHA POWDER COLOUR [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] NEHA SHAMPOO HAIR COLOR': 'Brand',
    '[HCEXL] NIKHAR HENNA [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] NISHA CREME': 'Brand',
    '[HCEXL] NISHA HENNA [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] NISHA POWDER': 'Brand',
    '[HCEXL] NISHA POWDER [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] NISHA SHAMPOO HAIR COLOR': 'Brand',
    '[HCEXL] NUPUR HBP [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] ORIFLAME': 'Brand',
    '[HCEXL] OTH.BRDED CLR\'ANT/HENNA': 'Others',
    '[HCEXL] OTH.BRDED CLR\'ANT/HENNA [ANY HERBAL BASED PWD]': 'Others',
    '[HCEXL] PALETTE': 'Brand',
    '[HCEXL] PANCHVATI HERBAL COLOUR CREAM': 'Brand',
    '[HCEXL] PANCHVATI KALI MEHANDI': 'Brand',
    '[HCEXL] PATANJALI': 'Brand',
    '[HCEXL] PATANJALI [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] PREM DULHAN [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] PREM KAVERI [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] PUSHP HENNA POWDER [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] PUSHP HENNA [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] SILKIENCE': 'Brand',
    '[HCEXL] SISO': 'Brand',
    '[HCEXL] SPINZ NOURISHING HAIR COLOR CR': 'Brand',
    '[HCEXL] STERLING HENNA [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] STREAX HAIR COLOUR': 'Brand',
    '[HCEXL] SUPER VASMOL 33 BROWN AYURPRASH': 'Brand',
    '[HCEXL] SUPER VASMOL AMLA DYE': 'Brand',
    '[HCEXL] SUPER VASMOL AMLA HERBAL BROWN [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] SUPER VASMOL33 KALI MEHANDI': 'Brand',
    '[HCEXL] SUPER VASMOL33 KESH KALA': 'Brand',
    '[HCEXL] VASMOL': 'Brand',
    '[HCEXL] VASMOL AYURPRASH SHAMPOO HAIR': 'Brand',
    '[HCEXL] VASMOL [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] VCARE COLORING SHAMPOO': 'Brand',
    '[HCEXL] VIP HAIR COLOUR SHAMPOO': 'Brand',
    '[HCEXL] VLCC HENNA [ANY HERBAL BASED PWD]': 'Brand',
    '[HCEXL] WELLA': 'Brand',
    '[HCEXL] ZEBA [ANY HERBAL BASED PWD]': 'Brand',
    '[HEXLI] ADORE HENNA': 'Brand',
    '[HEXLI] AMINA HENNA': 'Brand',
    '[HEXLI] ANOO\'S HEENA': 'Brand',
    '[HEXLI] ANY HENNA': 'Category',
    '[HEXLI] ASHOK HINA': 'Brand',
    '[HEXLI] AVON HENNA POWDER': 'Brand',
    '[HEXLI] AYUR HENNA POWDER': 'Brand',
    '[HEXLI] AYUR RAJAS NAT HENNA PWD': 'Brand',
    '[HEXLI] BANJARA HENNA': 'Brand',
    '[HEXLI] BHAWNAGAR HENNA': 'Brand',
    '[HEXLI] BLACK DIAMOND HENNA': 'Brand',
    '[HEXLI] BLACK GOLD HENNA': 'Brand',
    '[HEXLI] BLACK NIGHT HENNA': 'Brand',
    '[HEXLI] BLACK ROSE HERBAL HENNA P': 'Brand',
    '[HEXLI] BRITE HENNA': 'Brand',
    '[HEXLI] COLORINA HENNA': 'Brand',
    '[HEXLI] DIAMOND HENNA HAIR COLOR': 'Brand',
    '[HEXLI] DOUBLE HATTI MEHANDI': 'Brand',
    '[HEXLI] DULHAN HENNA POWDER': 'Brand',
    '[HEXLI] EVEREST HENNA': 'Brand',
    '[HEXLI] EXCEL': 'Brand',
    '[HEXLI] GANPATI CHHAP MEHANDI': 'Brand',
    '[HEXLI] GODREJ NUPUR MEHENDI': 'Brand',
    '[HEXLI] HERBAL HENNA POWDER': 'Brand',
    '[HEXLI] HERBY HENNA PLUS': 'Brand',
    '[HEXLI] JANNU MEHANDI': 'Brand',
    '[HEXLI] JOVEES': 'Brand',
    '[HEXLI] KANTA HENNA PLUS': 'Brand',
    '[HEXLI] L.D.H HENNA POWDER': 'Brand',
    '[HEXLI] MILAN HENNA': 'Brand',
    '[HEXLI] MINAR HENNA POWDER': 'Brand',
    '[HEXLI] NEERA': 'Brand',
    '[HEXLI] NIKHAR HENNA': 'Brand',
    '[HEXLI] NISHA POWDER': 'Brand',
    '[HEXLI] NOORJAHAN HENNA': 'Brand',
    '[HEXLI] NYLE HENNA': 'Brand',
    '[HEXLI] OTH.BRDED CLR\'ANT/HENNA': 'Others',
    '[HEXLI] PAKEEJA HENNA': 'Brand',
    '[HEXLI] PANCHVATI HENNA POWDER': 'Brand',
    '[HEXLI] PARAMPARA': 'Brand',
    '[HEXLI] PATANJALI': 'Brand',
    '[HEXLI] POOJA NIKHAR HENNA': 'Brand',
    '[HEXLI] PREM DULHAN': 'Brand',
    '[HEXLI] RADHIKA': 'Brand',
    '[HEXLI] RAJASTHANI HENNA': 'Brand',
    '[HEXLI] RANGOLI HENNA': 'Brand',
    '[HEXLI] RAWALDAS HENNA': 'Brand',
    '[HEXLI] SAHIBA HENNA': 'Brand',
    '[HEXLI] SHANKAR SUGANDHI HENNA': 'Brand',
    '[HEXLI] SHELLY HENNA': 'Brand',
    '[HEXLI] SHENAI HERBAL HENNA': 'Brand',
    '[HEXLI] SHINGAR HENNA POWDER': 'Brand',
    '[HEXLI] UNBRANDED CLR\'ANT/HENNA': 'Brand',
    '[HEXLI] VASMOL SHEHNAI': 'Brand',
    '[HEXLI] VLCC HENNA': 'Brand',
}